### ISSUE TITLE
Mini group buy?

### ISSUE THREAD

**Issue by jdayton3** [peej/for-science-keyboard#3]
Hey! I have been eyeing this keyboard for a while, and I went to place an order for it the other day and realized that shipping is pretty expensive for small orders of PCBs. I started mulling over the idea of doing a small group buy so shipping costs could be divided among several orders, and I thought that before I moved forward with that, I should contact you and see how you feel about it, since it's your keyboard!

Let me know what you think - you can contact me on Reddit (u/knot-a-robot) or find my other contact info at my woefully out-of-date personal website, http://jdaytn.com/

**Comment by peej** [comment]
No problem. The keyboard is pretty unusable but it's a fun little project.

JLCPCB do pretty cheap shipping for 5 sub-100x100 PCBs if you pick their slow shipping.

**Comment by jdayton3** [comment]
Awesome, thanks! I've noticed an uptick in 10-column keebs lately (Little_Foot, GergoPlex, Atreus, to name a few) and thought it'd be neat to see what all the rage is about on the cheap!

**Comment by jdayton3** [comment]
Oh hey, what length of M2 screws / standoffs does this require?

**Comment by jdayton3** [comment]
Wasn't sure if you'd get notifications for a closed issue, so reopening

**Comment by peej** [comment]
The standoffs need to be long enough to clear the Promicro chip side up, so it depends on how closely you can solder it to the PCB. If you use the standard Promicro headers then 8mm standoffs should provide enough of room, if you forgo the headers and solder the Promicro closer to the PCB you could probably get away with 5 or 6mm.

The screws need to be short enough to screw into the standoffs without hitting the opposing screw from the other side, so less than half the standoff length plus the PCB thickness.
