### ISSUE TITLE
Plate failed preflight check at JLCPCB

### ISSUE THREAD

**Issue by bmordue** [peej/for-science-keyboard#4]
I uploaded https://github.com/peej/for-science-keyboard/blob/master/gerber/for-science-plate.zip to JLPCB with PCB thickness 1.6mm.
I received a message from JLCPCB:
"Please kindly note that the connection tabs between the slots and the board edge is too small in you file which will make the board broken easily. In order to ensure the board quality, we advise you to enlarge the connection tabs to 3mm at least."

**Comment by peej** [comment]
I ordered mine from AllPCB and didn't have a problem ordering with these gerbers or with the resulting plates. I guess JLCPCB have a different set of checks.

I think you'll be fine but you can always adjust the plate file to make it bigger if you feel the need.

**Comment by bmordue** [comment]
Thanks for the reply!
I'll try tweaking the plate. Just wanted to flag it up.
