### ISSUE TITLE
"2M" screws and standoffs

### ISSUE THREAD

**Issue by semilin** [peej/for-science-keyboard#5]
Hi, I was trying to gather the parts to see how much it would cost to assemble this, and I was stuck trying to figure out where to get the 2M screws and standoffs. It seems I either get results for 2 millimeter ones, or "M2" screws. Are either of these what I am looking for? Sorry if this is a trivial question.

**Comment by peej** [comment]
Hi, yes sorry this is incorrect in the documentation, it should read M2. Best of luck with your build.
